[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot "ftl" --]
[#-- @ftlvariable name="metaEntity" type="com.youran.generate.pojo.po.MetaEntityPO"--]
[#-- @ftlvariable name="metaConst" type="com.youran.generate.pojo.po.MetaConstPO"--]
[#-- @ftlvariable name="metaEntities" type="java.util.List<com.youran.generate.pojo.po.MetaEntityPO>"--]
[#-- @ftlvariable name="metaConsts" type="java.util.List<com.youran.generate.pojo.po.MetaConstPO>"--]
[#-- @ftlvariable name="packageName" type="java.lang.String"--]
[#-- @ftlvariable name="commonPackage" type="java.lang.String"--]
[#-- @ftlvariable name="projectName" type="java.lang.String"--]
[#-- @ftlvariable name="originProjectName" type="java.lang.String"--]
[#-- @ftlvariable name="author" type="java.lang.String"--]
[#-- @ftlvariable name="mtms" type="java.util.List<com.youran.generate.pojo.po.MetaManyToManyPO>"--]
[#-- @ftlvariable name="MetadataUtil" type="com.youran.generate.util.MetadataUtil.static"--]
[#-- @ftlvariable name="JFieldType" type="com.youran.generate.constant.JFieldType.static"--]
[#-- @ftlvariable name="QueryType" type="com.youran.generate.constant.QueryType.static"--]
[#-- @ftlvariable name="MetaSpecialField" type="com.youran.generate.constant.MetaSpecialField.static"--]
