export default  {
  '主键ID(Long)':{
    jfieldName: 'id',
    fieldName: 'id',
    fieldDesc: '主键',
    jfieldType: 'Long',
    fieldType: 'bigint',
    fieldLength: 20,
    fieldScale: 0,
    primaryKey: 1,
    autoIncrement: 1,
    defaultValue:'',
    notNull: 1,
    specialField: '',
    fieldExample: '1',
    fieldComment: '主键ID',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 1,
    editType: null,
    orderNo: 1
  },
  '主键ID(Integer)':{
    jfieldName: 'id',
    fieldName: 'id',
    fieldDesc: '主键',
    jfieldType: 'Integer',
    fieldType: 'int',
    fieldLength: 11,
    fieldScale: 0,
    primaryKey: 1,
    autoIncrement: 1,
    defaultValue:'',
    notNull: 1,
    specialField: '',
    fieldExample: '1',
    fieldComment: '主键ID',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 1,
    editType: null,
    orderNo: 1
  },
  '创建时间':{
    jfieldName: 'createDate',
    fieldName: 'create_date',
    fieldDesc: '创建时间',
    jfieldType: 'Date',
    fieldType: 'datetime',
    fieldLength: 0,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'createDate',
    fieldExample: '2017-12-07 00:00:00',
    fieldComment: '创建时间【yyyy-MM-dd HH:mm:ss】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 100
  },
  '创建人':{
    jfieldName: 'createBy',
    fieldName: 'create_by',
    fieldDesc: '创建人',
    jfieldType: 'String',
    fieldType: 'varchar',
    fieldLength: 20,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'createBy',
    fieldExample: 'admin',
    fieldComment: '创建人【最大长度20】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 101
  },
  '修改时间':{
    jfieldName: 'operateDate',
    fieldName: 'operate_date',
    fieldDesc: '修改时间',
    jfieldType: 'Date',
    fieldType: 'datetime',
    fieldLength: 0,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'operateDate',
    fieldExample: '2017-12-07 00:00:00',
    fieldComment: '修改时间【yyyy-MM-dd HH:mm:ss】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 102
  },
  '修改人':{
    jfieldName: 'operateBy',
    fieldName: 'operate_by',
    fieldDesc: '修改人',
    jfieldType: 'String',
    fieldType: 'varchar',
    fieldLength: 20,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'operateBy',
    fieldExample: 'admin',
    fieldComment: '修改人【最大长度20】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 103
  },
  '乐观锁版本号':{
    jfieldName: 'version',
    fieldName: 'version',
    fieldDesc: '乐观锁版本号',
    jfieldType: 'Integer',
    fieldType: 'int',
    fieldLength: 11,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'version',
    fieldExample: '1',
    fieldComment: '乐观锁版本号【整型】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 104
  },
  '逻辑删除标识':{
    jfieldName: 'delSign',
    fieldName: 'del_sign',
    fieldDesc: '逻辑删除标识',
    jfieldType: 'Integer',
    fieldType: 'tinyint',
    fieldLength: 1,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: 'delSign',
    fieldExample: '0',
    fieldComment: '逻辑删除标识【0-未删除，1-已删除】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 0,
    update: 0,
    list: 0,
    show: 0,
    editType: null,
    orderNo: 105
  },
  '排序号':{
    jfieldName: 'orderNo',
    fieldName: 'order_no',
    fieldDesc: '排序号',
    jfieldType: 'Integer',
    fieldType: 'int',
    fieldLength: 11,
    fieldScale: 0,
    primaryKey: 0,
    autoIncrement: 0,
    defaultValue:'',
    notNull: 1,
    specialField: '',
    fieldExample: '1',
    fieldComment: '排序号【整型】',
    dicType: '',
    query: 0,
    queryType: null,
    insert: 1,
    update: 1,
    list: 1,
    show: 1,
    editType: null,
    orderNo: 90
  },
}
